name: Lockfile maintenance
on:
  schedule:
    - cron: "0 0 * * 5" # Friday 09:00 JST
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  maintenance:
    uses: knu/lockfile-maintenance-action/.github/workflows/maintenance.yml@6a0d92ca835c48e8c97a226c7e55154b13eead80 # main
    with:
      auth: oidc
      files: /pnpm-lock.yaml
