name: Lockfile maintenance
on:
  schedule:
    - cron: "0 0 * * 5" # Friday 09:00 JST
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  maintenance:
    uses: knu/lockfile-maintenance-action/.github/workflows/maintenance.yml@b25f71652280135d0af3ed9abee56849942c5624 # v2.0.0
    with:
      files: /pnpm-lock.yaml
